FROM python:3.9.0

RUN mkdir /root/.ssh/

ADD ./.ssh/id_rsa /root/.ssh/id_rsa

RUN chmod 600 /root/.ssh/id_rsa

RUN touch /root/.ssh/known_hosts

RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

WORKDIR /home/

RUN echo "testing1234"

RUN git clone git@github.com:HC-kang/pinter_private.git

WORKDIR /home/pinter_private/

RUN pip install -r requirements.txt

RUN pip install gunicorn

RUN pip install mysqlclient

WORKDIR /home/pinter/inventory/

EXPOSE 8000

CMD ["bash", "-c", "python manage.py collectstatic --noinput --settings=inventory.settings.deploy && python manage.py migrate --settings=inventory.settings.deploy && gunicorn inventory.wsgi --env DJANGO_SETTINGS_MODULE=inventory.settings.deploy --bind 0.0.0.0:8000"]