version: '3.9'

services:

  http1:
    image: node
    command: node --watch http-1.js
    ports:
      - "3001:3001"
    networks:
      - node_network
    volumes:
      - .:/app
    working_dir: /app

  http2:
    image: node
    command: node --watch http-2.js
    ports:
      - "3002:3002"
      - "8443:443"
    networks:
      - node_network
    volumes:
      - .:/app
    working_dir: /app

  http3:
    image: node
    command: node --watch http-3.js
    ports:
      - "3003:3003"
      - "8444:443"
    networks:
      - node_network
    volumes:
      - .:/app
    working_dir: /app

  gateway:
    image: node
    command: node --watch http-gateway.js
    ports:
      - "3000:3000"
    networks:
      - node_network
    volumes:
      - .:/app
    working_dir: /app

networks:
  node_network:
    driver: bridge
